### ISSUE TITLE
Names should not ever start or end with spaces

### ISSUE THREAD

**Issue by sapphonie** [JoinedSenses/TF2-Regex-Filter#5]
Replacing characters in names with "" (aka removing them) causes this.

Try running TrimString immediately before this line, maybe? Not sure

https://github.com/JoinedSenses/SM-Regex-Trigger/blob/0a26152df85951b3b1964d93970e55d895fc1590/scripting/regextrigger.sp#L849

**Comment by JoinedSenses** [comment]
I guess I've never noticed it because I use this in my own config:
> "namepattern"           "^[ ]+"
