### ISSUE TITLE
Clients show up as "unnamed" regardless of preset name list

### ISSUE THREAD

**Issue by sapphonie** [JoinedSenses/TF2-Regex-Filter#6]
Removing chars from clients names with "replace" "" causes some clients with empty names to be named "unnamed" instead of names on this list:

https://github.com/JoinedSenses/SM-Regex-Trigger/blob/master/scripting/regextrigger.sp#L67-L90

No idea what causes this, for the record, "sm_regex_prefix" is set to "RENAMED_"

**Comment by JoinedSenses** [comment]
Its probably related to not trimming spaces from the name. I'll investigate and test.
